### ISSUE TITLE
Add publication info

### ISSUE THREAD

**Issue by vuillaut** [cta-observatory/lst-crab-performance-paper-2023#10]
We should add the following entry in citation.cff when the paper is accepted for publication:

- `preferred-citation`
- `identifiers`

**Comment by morcuended** [comment]
@vuillaut do we have to change the fields in the `preferred-citation` section from arXiv to ApJ info?

https://github.com/cta-observatory/lst-crab-performance-paper-2023/blob/e84be3476e275b76cacf9024278e07717dce20f9/CITATION.cff#L59-L65

**Comment by vuillaut** [comment]
yes! could you do it please?

**Comment by morcuended** [comment]
done in #22
