### ISSUE TITLE
Provide the EDISP-corrected SED and LC results in this repo?

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/lst-crab-performance-paper-2023#23]
I think it would be helpful for comparisons with current results

**Comment by rlopezcoto** [comment]
I think that in this repo we should stick to the results of the paper, otherwise it will be confusing to people coming here to get them

**Comment by morcuended** [comment]
That's true, but do we want to share in some way and somewhere the corrected results so people can access them?
