### ISSUE TITLE
Intended changes?

### ISSUE THREAD

**Issue by morcuended** [cta-observatory/lst-crab-performance-paper-2023#24]
Were changes in commit [0c55cc7](https://github.com/cta-observatory/lst-crab-performance-paper-2023/commit/0c55cc7cada33fe137850ab290363b946ba3ac17) intended?

**Comment by vuillaut** [comment]
> Were changes in commit [0c55cc7](https://github.com/cta-observatory/lst-crab-performance-paper-2023/commit/0c55cc7cada33fe137850ab290363b946ba3ac17) intended?

Holy sh*t no!

**Comment by vuillaut** [comment]
I will undo that and protect the main branch (which should have been done!)

**Comment by morcuended** [comment]
I added the rule protection yesterday

**Comment by vuillaut** [comment]
I see the branch is protected and can still push to main (I just did to revert commit [0c55cc7](https://github.com/cta-observatory/lst-crab-performance-paper-2023/commit/0c55cc7cada33fe137850ab290363b946ba3ac17))

**Comment by vuillaut** [comment]
Ok, I enforced the protection by setting:
- [ ] Lock branch. Branch is read-only. Users cannot push to the branch. 
The repo is not supposed to change anyway. If ever, one can go and remove that protection.
- [ ] Do not allow bypassing the above settings. The above settings will apply to administrators and custom roles with the "bypass branch protections" permission.
